import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const U='https://upnfwizmumysgwudyfsp.supabase.co',K='sb_publishable_wDbR7xAPEq8ZN2SjqlBLwA_EbRX-dqp',APP=window.location.origin,sb=createClient(U,K),root=document.getElementById('root');
let session,profile,cands=[],ci=0,cur,timer;
const areas=['Almada','Cacilhas','Cova da Piedade','Costa da Caparica','Lisboa Centro','Areeiro','Alvalade','Benfica','Belém','Oeiras','Amadora','Odivelas','Loures','Sintra'];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),ini=n=>String(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase(),pic=p=>p?sb.storage.from('profile-photos').getPublicUrl(p).data.publicUrl:null;
function toast(t){let e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function pop(t,p,h=''){let d=document.createElement('div');d.className='modalbg';d.innerHTML='<div class="modal"><h3>'+esc(t)+'</h3><p>'+p+'</p>'+h+'<button class="btn ghost w" id="x">Fechar</button></div>';document.body.appendChild(d);d.querySelector('#x').onclick=()=>d.remove();d.onclick=e=>{if(e.target===d)d.remove()}}
async function blockUser(userId,name){if(!userId||userId===session?.user?.id)return;let ok=window.confirm('Bloquear '+name+'? Vocês deixarão de aparecer um para o outro e não poderão enviar novas mensagens.');if(!ok)return;let q=await sb.from('blocks').insert({blocker_id:session.user.id,blocked_id:userId});if(q.error&&q.error.code!=='23505')return toast('Não foi possível bloquear agora.');cands=[];cur=null;toast('Utilizador bloqueado.');matches()}
function reportUser(userId,matchId,name){if(!userId||userId===session?.user?.id)return;let d=document.createElement('div');d.className='modalbg';d.innerHTML='<div class="modal"><h3>Denunciar perfil</h3><p>Ajude-nos a manter o CasaMatch seguro. A denúncia não é mostrada a '+esc(name)+'.</p><form id="reportForm"><div class="field"><label>Motivo</label><select name="reason" required><option value="perfil_falso">Perfil falso ou suspeito</option><option value="assédio">Assédio ou comportamento abusivo</option><option value="fraude">Fraude ou pedido de dinheiro</option><option value="conteudo_inadequado">Conteúdo inadequado</option><option value="outro">Outro</option></select></div><div class="field"><label>Detalhes (opcional)</label><textarea name="details" maxlength="1000" placeholder="Explique brevemente o que aconteceu."></textarea></div><button class="btn red w">Enviar denúncia</button><div style="height:8px"></div><button class="btn ghost w" type="button" id="cancelReport">Cancelar</button></form></div>';document.body.appendChild(d);d.querySelector('#cancelReport').onclick=()=>d.remove();d.onclick=e=>{if(e.target===d)d.remove()};d.querySelector('#reportForm').onsubmit=async e=>{e.preventDefault();let fd=new FormData(e.currentTarget),btn=e.submitter;btn.disabled=true;let payload={reporter_id:session.user.id,reported_id:userId,match_id:matchId||null,reason:fd.get('reason'),details:fd.get('details')?.trim()||null},q=await sb.from('reports').insert(payload);if(q.error){btn.disabled=false;return toast('Não foi possível enviar a denúncia.')}d.remove();toast('Denúncia enviada. Obrigada por avisar.')}}
function safetyActions(userId,matchId,name){let d=document.createElement('div');d.className='modalbg';d.innerHTML='<div class="modal"><h3>Segurança</h3><p>Nunca envie dinheiro ou documentos pelo chat. Confirme pessoa, imóvel e contrato antes de assumir qualquer compromisso.</p><button class="btn ghost w" id="reportAction">Denunciar '+esc(name)+'</button><div style="height:8px"></div><button class="btn soft w" id="blockAction">Bloquear '+esc(name)+'</button><div style="height:8px"></div><button class="btn ghost w" id="closeAction">Fechar</button></div>';document.body.appendChild(d);d.querySelector('#closeAction').onclick=()=>d.remove();d.querySelector('#reportAction').onclick=()=>{d.remove();reportUser(userId,matchId,name)};d.querySelector('#blockAction').onclick=()=>{d.remove();blockUser(userId,name)};d.onclick=e=>{if(e.target===d)d.remove()}}
function legal(type){
  if(type==='privacy')pop('Privacidade','No beta, usamos os dados do perfil apenas para criar compatibilidade, mostrar perfis e permitir matches. Não publiques morada exata, documentos, dados bancários ou informação sensível no perfil. Podes sair da conta a qualquer momento.','');
  else if(type==='terms')pop('Termos do beta','CasaMatch é um serviço beta para aproximar pessoas interessadas em dividir casa. A plataforma não é imobiliária, não garante identidade, solvência, imóvel, contrato ou segurança de terceiros. Confirma sempre as informações antes de pagar, assinar ou encontrar alguém presencialmente.','');
  else pop('Segurança','Nunca envies dinheiro para reservar uma casa sem confirmar a pessoa, o imóvel e o contrato. Faz a primeira visita/encontro em local seguro, avisa alguém de confiança e não partilhes documentos ou dados bancários no chat.','');
}
function landing(){
root.innerHTML=`<header class="top"><div class="logo">Casa<b>Match</b></div><button class="btn ghost" id="login">Entrar</button></header>
<main class="landing">
<section class="hero-wrap">
<div class="hero">
<span class="pill">🏠 Grande Lisboa · beta</span>
<h1>Encontre a pessoa certa para <em>dividir casa.</em></h1>
<p>Antes de procurar quatro paredes, encontre alguém com orçamento, zonas e hábitos compatíveis com os seus.</p>
<div class="actions"><button class="btn red" id="signup">Entrar no beta grátis</button><button class="btn ghost" id="how">Como funciona</button></div>
<div class="micro"><span>✓ 18+</span><span>✓ sem pagamento no beta</span><span>✓ compatibilidade de hábitos</span></div>
</div>
<div class="preview"><div class="demo-card"><div class="demo-photo"><div class="person">CM</div><div class="demo-score">92% compatível</div></div><div class="demo-body"><div class="demo-name">A pessoa certa pode estar perto.</div><div class="demo-meta">📍 Grande Lisboa · orçamento e estilo de vida compatíveis</div><div class="traits"><span class="trait">🚭 não fuma</span><span class="trait">🐾 aceita pets</span><span class="trait">☀️ dorme cedo</span></div></div></div></div>
</section>
<section class="section"><span class="pill">Compatibilidade primeiro</span><h2>Não é só encontrar um quarto. É conseguir viver bem com alguém.</h2><p>O CasaMatch cruza preferências de zona, orçamento e rotina para mostrar pessoas com maior probabilidade de funcionar na vida real.</p>
<div class="steps"><div class="step"><div class="n">1</div><h3>Crie o seu perfil</h3><p>Diga onde procura, quanto pode pagar e como gosta de viver em casa.</p></div><div class="step"><div class="n">2</div><h3>Descubra pessoas</h3><p>Veja perfis ordenados por compatibilidade e escolha quem faz sentido para si.</p></div><div class="step"><div class="n">3</div><h3>Conversem no match</h3><p>Quando os dois gostarem, o chat fica disponível para combinarem os próximos passos.</p></div></div>
</section>
<div class="cta"><h2>Primeiras vagas do beta abertas.</h2><p>Estamos a começar pela Grande Lisboa. Entra agora, cria o teu perfil e ajuda-nos a construir uma forma melhor de encontrar roommate.</p><button class="btn red" id="signup2">Criar conta grátis</button></div>
</main>
<footer class="foot"><div class="footin"><div>CasaMatch · beta 2026</div><div class="footlinks"><button data-l="privacy">Privacidade</button><button data-l="terms">Termos</button><button data-l="safety">Segurança</button></div></div></footer>`;
document.getElementById('login').onclick=()=>auth('login');document.getElementById('signup').onclick=()=>auth('signup');document.getElementById('signup2').onclick=()=>auth('signup');
document.getElementById('how').onclick=()=>document.querySelector('.section').scrollIntoView({behavior:'smooth'});document.querySelectorAll('[data-l]').forEach(x=>x.onclick=()=>legal(x.dataset.l));
}
function auth(m,msg=''){let s=m==='signup';root.innerHTML='<main class="auth"><div class="card"><button class="link" id="bk">← voltar</button><h2>'+(s?'Criar conta':'Entrar')+'</h2><p class="sub">'+(s?'Grátis durante o beta. É necessário ter 18 anos ou mais.':'Continue a sua procura por alguém compatível.')+'</p>'+(msg?'<div class="notice">'+esc(msg)+'</div>':'')+'<form id="af"><div class="field"><label>Email</label><input id="em" type="email" autocomplete="email" required></div><div class="field"><label>Palavra-passe</label><input id="pw" type="password" minlength="8" autocomplete="'+(s?'new-password':'current-password')+'" required></div><button class="btn red w">'+(s?'Criar conta':'Entrar')+'</button></form><div class="notice">Ao continuar, aceita os termos do beta e confirma que tem 18 anos ou mais.</div></div></main>';document.getElementById('bk').onclick=landing;document.getElementById('af').onsubmit=async e=>{e.preventDefault();let email=document.getElementById('em').value.trim(),password=document.getElementById('pw').value,btn=e.submitter;btn.disabled=true;try{if(s){let r=await sb.auth.signUp({email,password,options:{emailRedirectTo:APP}});if(r.error)throw r.error;if(r.data.session){session=r.data.session;after()}else auth('login','Conta criada. Confirme o email para continuar.')}else{let r=await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error;session=r.data.session;after()}}catch(x){auth(m,x.message)}finally{btn.disabled=false}}}
async function after(){let r=await sb.auth.getSession();session=r.data.session;if(!session)return landing();let q=await sb.from('profiles').select('*').eq('id',session.user.id).maybeSingle();if(q.error)return toast('Não foi possível carregar o perfil.');profile=q.data;if(!profile?.onboarding_complete)onboard();else app('discover')}
function onboard(){let p=profile||{};root.innerHTML='<header class="top"><div class="logo">Casa<b>Match</b></div><button class="btn ghost" id="out">Sair</button></header><main class="on"><span class="pill">O seu perfil</span><h1>Vamos encontrar alguém compatível.</h1><p class="onlead">Quanto melhor o perfil, melhor a ordem dos matches. Não inclua morada exata, documentos ou contactos pessoais na bio.</p><form id="of">'+
'<div class="formblock"><h3>Sobre si</h3><div class="row"><div class="field"><label>Nome</label><input name="display_name" maxlength="40" required value="'+esc(p.display_name||'')+'"></div><div class="field"><label>Nascimento</label><input name="birth_date" type="date" required value="'+(p.birth_date||'')+'"></div></div><div class="row"><div class="field"><label>Género</label><select name="gender"><option value="mulher">Mulher</option><option value="homem">Homem</option><option value="nao_binario">Não binário</option><option value="prefiro_nao_dizer">Prefiro não dizer</option></select></div><div class="field"><label>Quem prefere encontrar</label><select name="preferred_gender"><option value="qualquer">Qualquer género</option><option value="mulher">Mulher</option><option value="homem">Homem</option><option value="nao_binario">Não binário</option></select></div></div><div class="field"><label>Foto</label><input name="photo" type="file" accept="image/*"><span class="small">Recomendado: rosto visível e foto recente. Máx. 5 MB.</span></div></div>'+ 
'<div class="formblock"><h3>Procura</h3><div class="row"><div class="field"><label>Zona atual</label><select name="area">'+areas.map(a=>'<option>'+a+'</option>').join('')+'</select></div><div class="field"><label>Orçamento máximo €</label><input name="max_budget" type="number" min="150" max="5000" required value="'+(p.max_budget||650)+'"></div></div><div class="field"><label>Zonas onde procura</label><div class="chips">'+areas.map(a=>'<label class="chip"><input type="checkbox" name="preferred_areas" value="'+a+'"><span>'+a+'</span></label>').join('')+'</div></div><div class="field"><label>Quando pretende mudar</label><input name="move_in_date" type="date" value="'+(p.move_in_date||'')+'"></div></div>'+ 
'<div class="formblock"><h3>Como é viver consigo?</h3><div class="row"><div class="field"><label>Horário</label><select name="sleep_schedule"><option value="cedo">Durmo cedo</option><option value="flexivel">Flexível</option><option value="tarde">Durmo tarde</option></select></div><div class="field"><label>Trabalho/estudo</label><select name="work_mode"><option value="fora">Maioritariamente fora</option><option value="hibrido">Híbrido</option><option value="casa">Maioritariamente em casa</option></select></div></div><div class="field"><label>Visitas em casa</label><select name="guests_frequency"><option value="raramente">Raramente</option><option value="as_vezes">Às vezes</option><option value="frequente">Frequentemente</option></select></div><div class="field"><label>Nível de limpeza</label><input name="cleanliness" type="range" min="1" max="5" value="'+(p.cleanliness||3)+'"><div class="rangehint"><span>relaxado</span><span>muito organizado</span></div></div><div class="field"><label>Ambiente da casa</label><input name="social_level" type="range" min="1" max="5" value="'+(p.social_level||3)+'"><div class="rangehint"><span>muito tranquilo</span><span>muito social</span></div></div><div class="chips" style="margin:14px 0"><label class="chip"><input type="checkbox" name="smokes"><span>🚬 Fumo</span></label><label class="chip"><input type="checkbox" name="has_pets"><span>🐾 Tenho animal</span></label><label class="chip"><input type="checkbox" name="accepts_pets"><span>🐶 Aceito animais</span></label></div><div class="field"><label>Uma pequena bio</label><textarea name="bio" maxlength="280" placeholder="Ex.: trabalho em Lisboa, procuro uma casa tranquila e gosto de cozinhar...">'+esc(p.bio||'')+'</textarea></div></div>'+ 
'<button class="btn red w">Guardar e descobrir pessoas</button><div id="err"></div></form></main>';
document.getElementById('out').onclick=logout;let f=document.getElementById('of');if(p.gender)f.gender.value=p.gender;if(p.preferred_gender)f.preferred_gender.value=p.preferred_gender;if(p.area)f.area.value=p.area;if(p.sleep_schedule)f.sleep_schedule.value=p.sleep_schedule;if(p.work_mode)f.work_mode.value=p.work_mode;if(p.guests_frequency)f.guests_frequency.value=p.guests_frequency;f.smokes.checked=!!p.smokes;f.has_pets.checked=!!p.has_pets;f.accepts_pets.checked=p.accepts_pets!==false;(p.preferred_areas||[]).forEach(a=>{let x=[...f.querySelectorAll('[name=preferred_areas]')].find(y=>y.value===a);if(x)x.checked=true});
f.onsubmit=async e=>{e.preventDefault();let fd=new FormData(f),cut=new Date();cut.setHours(0,0,0,0);cut.setFullYear(cut.getFullYear()-18);let birth=new Date(fd.get('birth_date')+'T00:00:00');if(!birth.getTime()||birth>cut){document.getElementById('err').innerHTML='<div class="notice warn">É necessário ter 18 anos ou mais.</div>';return}if(fd.getAll('preferred_areas').length===0){document.getElementById('err').innerHTML='<div class="notice warn">Escolha pelo menos uma zona onde procura.</div>';return}let btn=e.submitter;btn.disabled=true;btn.textContent='A guardar...';try{let pp=p.photo_path||null,file=f.photo.files[0];if(file){if(file.size>5*1024*1024)throw new Error('A foto deve ter no máximo 5 MB.');let path=session.user.id+'/'+Date.now()+'-'+file.name.replace(/[^a-z0-9._-]/gi,'_'),u=await sb.storage.from('profile-photos').upload(path,file,{upsert:true});if(u.error)throw u.error;pp=path}let data={id:session.user.id,display_name:fd.get('display_name').trim(),birth_date:fd.get('birth_date'),gender:fd.get('gender'),city:'Grande Lisboa',area:fd.get('area'),preferred_areas:fd.getAll('preferred_areas'),max_budget:+fd.get('max_budget'),move_in_date:fd.get('move_in_date')||null,bio:fd.get('bio').trim(),photo_path:pp,smokes:fd.get('smokes')==='on',has_pets:fd.get('has_pets')==='on',accepts_pets:fd.get('accepts_pets')==='on',cleanliness:+fd.get('cleanliness'),social_level:+fd.get('social_level'),sleep_schedule:fd.get('sleep_schedule'),work_mode:fd.get('work_mode'),guests_frequency:fd.get('guests_frequency'),preferred_gender:fd.get('preferred_gender'),onboarding_complete:true,is_active:true},q=await sb.from('profiles').upsert(data).select().single();if(q.error)throw q.error;profile=q.data;cands=[];app('discover')}catch(x){document.getElementById('err').innerHTML='<div class="notice warn">'+esc(x.message)+'</div>'}finally{btn.disabled=false;btn.textContent='Guardar e descobrir pessoas'}}}
function chrome(c,t){clearInterval(timer);root.innerHTML='<div class="app"><header class="head"><div class="logo">Casa<b>Match</b></div><div class="quota" id="quota">...</div></header><main class="main" id="main">'+c+'</main><nav class="bottom"><div class="bin"><button class="nav '+(t==='discover'?'active':'')+'" data-t="discover"><span>⌁</span>Descobrir</button><button class="nav '+(t==='matches'?'active':'')+'" data-t="matches"><span>♡</span>Matches</button><button class="nav '+(t==='profile'?'active':'')+'" data-t="profile"><span>◉</span>Perfil</button></div></nav></div>';document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>app(x.dataset.t));quota()}
async function quota(){let q=await sb.rpc('free_contact_status'),s=q.data?.[0],e=document.getElementById('quota');if(e)e.textContent=s?(s.plus?'CasaMatch+':'Conversas '+s.remaining+'/3'):'beta'}
function app(t){if(t==='discover')discover();if(t==='matches')matches();if(t==='profile')profileView()}
async function discover(force=false){chrome('<h1 class="title">Descobrir</h1><div class="empty">A procurar perfis compatíveis...</div>','discover');if(force||!cands.length||ci>=cands.length){let q=await sb.rpc('get_candidates',{limit_count:30});if(q.error){document.getElementById('main').innerHTML='<div class="empty"><h3>Não conseguimos carregar os perfis.</h3><p>'+esc(q.error.message)+'</p></div>';return}cands=q.data||[];ci=0}draw()}
function traits(c){let a=[];a.push(c.smokes?'🚬 fuma':'🚭 não fuma');if(c.has_pets)a.push('🐾 tem pet');else if(c.accepts_pets)a.push('🐾 aceita pets');a.push(c.sleep_schedule==='tarde'?'🌙 dorme tarde':c.sleep_schedule==='cedo'?'☀️ dorme cedo':'⏰ horário flexível');a.push(c.work_mode==='casa'?'🏠 trabalha em casa':c.work_mode==='hibrido'?'💻 híbrido':'🚇 trabalha fora');return a}
function draw(){let c=cands[ci];if(!c){document.getElementById('main').innerHTML='<h1 class="title">Descobrir</h1><div class="empty"><h3>Por agora é tudo.</h3><p>O beta ainda está a crescer. Volte mais tarde ou convide alguém que também esteja à procura de roommate.</p></div>';return}let ph=pic(c.photo_path);document.getElementById('main').innerHTML='<h1 class="title">Descobrir</h1><div id="card" class="cand"><div class="photo">'+(ph?'<img src="'+ph+'" alt="Foto de '+esc(c.display_name)+'">':'<div class="ini">'+esc(ini(c.display_name))+'</div>')+'<div class="score">'+c.score+'% compatível</div></div><div class="body"><div class="name">'+esc(c.display_name)+', '+c.age+'</div><div class="meta">📍 '+esc(c.area||c.city)+' · até '+c.max_budget+' €/mês</div><div class="traits">'+traits(c).map(x=>'<span class="trait">'+x+'</span>').join('')+'</div><div class="bio">'+esc(c.bio||'Ainda não escreveu uma bio.')+'</div><div class="why">Compatibilidade baseada em orçamento, zona e hábitos do perfil. <button class="link" id="reportCard" style="float:right;font-size:12px">Denunciar</button></div></div></div><div class="sw"><button class="circle" id="rew" aria-label="Desfazer último passar">↶</button><button class="btn ghost" id="pass">Passar</button><button class="circle like" id="like" aria-label="Gostar">♥</button></div>';document.getElementById('pass').onclick=()=>swipe('pass');document.getElementById('like').onclick=()=>swipe('like');document.getElementById('rew').onclick=rewind;document.getElementById('reportCard').onclick=()=>reportUser(c.id,null,c.display_name);drag(document.getElementById('card'))}
function drag(el){let s=0,d=0,on=false;el.onpointerdown=e=>{on=true;s=e.clientX;el.setPointerCapture(e.pointerId)};el.onpointermove=e=>{if(on){d=e.clientX-s;el.style.transform='translateX('+d+'px) rotate('+(d/35)+'deg)'}};el.onpointerup=()=>{on=false;if(Math.abs(d)>95)swipe(d>0?'like':'pass');else el.style.transform='';d=0}}
async function rewind(){let s=await sb.rpc('free_contact_status');if(!s.data?.[0]?.plus)return plus();let r=await sb.rpc('rewind_last_pass');if(r.error)return toast(r.error.message);if(!r.data)return toast('Nada para desfazer');cands=[];await discover(true)}
async function swipe(direction){let c=cands[ci];if(!c)return;let q=await sb.from('swipes').insert({actor_id:session.user.id,target_id:c.id,direction});if(q.error)return toast(q.error.message);if(direction==='like'){let m=await sb.rpc('get_my_matches');if(!m.error&&(m.data||[]).some(x=>x.other_id===c.id))pop('É match!','Vocês gostaram um do outro. Já podem conversar.','<button class="btn red w" id="gomatch">Ver matches</button><div style="height:8px"></div>'),setTimeout(()=>{let b=document.getElementById('gomatch');if(b)b.onclick=()=>{document.querySelector('.modalbg')?.remove();matches()}},0)}ci++;draw()}
async function matches(){chrome('<h1 class="title">Matches</h1><div class="empty">A carregar...</div>','matches');let [m,l]=await Promise.all([sb.rpc('get_my_matches'),sb.rpc('incoming_like_count')]);if(m.error){document.getElementById('main').innerHTML='<div class="empty"><h3>Não conseguimos carregar os matches.</h3><p>'+esc(m.error.message)+'</p></div>';return}let a=m.data||[],h='<h1 class="title">Matches</h1>';if(!l.error&&(l.data||0)>0)h+='<div class="notice">♡ '+l.data+' pessoa(s) gostou de si. O detalhe de quem gostou faz parte do CasaMatch+.</div>';h+=a.length?a.map(x=>{let ph=pic(x.photo_path);return '<div class="match" data-id="'+x.match_id+'"><div class="av">'+(ph?'<img src="'+ph+'" alt="">':esc(ini(x.display_name)))+'</div><div class="grow"><b>'+esc(x.display_name)+', '+x.age+' · '+x.score+'%</b><div class="small">'+esc(x.area||'Grande Lisboa')+' · até '+x.max_budget+' €</div><div class="last">'+esc(x.last_message||'Diga olá 👋')+'</div></div><span>›</span></div>'}).join(''):'<div class="empty"><h3>Ainda sem matches.</h3><p>Continue a descobrir perfis. O chat abre quando o like é recíproco.</p></div>';document.getElementById('main').innerHTML=h;document.getElementById('main').querySelectorAll('.match').forEach(e=>e.onclick=()=>chat(e.dataset.id,a.find(x=>x.match_id===e.dataset.id)))}
async function chat(id,m){cur={id,m};chrome('','matches');document.getElementById('main').innerHTML='<div class="chat"><div class="chathead"><button class="link" id="back">← Matches</button><b>'+esc(m.display_name)+'</b><button class="link" id="safe">•••</button></div><div class="chattools"><button class="miniBtn" id="reportChat">Denunciar</button><button class="miniBtn danger" id="blockChat">Bloquear</button></div><div id="msgs" class="msgs"></div><form id="cf" class="compose"><input id="msg" maxlength="1500" autocomplete="off" placeholder="Escreva uma mensagem..."><button>Enviar</button></form></div>';document.getElementById('back').onclick=matches;document.getElementById('safe').onclick=()=>safetyActions(m.other_id,id,m.display_name);document.getElementById('reportChat').onclick=()=>reportUser(m.other_id,id,m.display_name);document.getElementById('blockChat').onclick=()=>blockUser(m.other_id,m.display_name);document.getElementById('cf').onsubmit=send;await load();timer=setInterval(load,4000)}
async function load(){let q=await sb.from('messages').select('sender_id,body,created_at').eq('match_id',cur.id).order('created_at'),mb=document.getElementById('msgs');if(!mb)return;if(q.error){mb.innerHTML='<div class="notice warn">'+esc(q.error.message)+'</div>';return}mb.innerHTML=(q.data||[]).map(x=>'<div class="bubble '+(x.sender_id===session.user.id?'me':'')+'">'+esc(x.body)+'</div>').join('')||'<div class="small" style="text-align:center;margin-top:20px">O match está feito. Comece quando quiser.</div>';mb.scrollTop=mb.scrollHeight}
async function send(e){e.preventDefault();let mi=document.getElementById('msg'),b=mi.value.trim();if(!b)return;let btn=e.submitter;btn.disabled=true;let q=await sb.from('messages').insert({match_id:cur.id,sender_id:session.user.id,body:b});btn.disabled=false;if(q.error){let t=(q.error.message||'').toLowerCase();if(t.includes('row-level')||t.includes('policy')||t.includes('can_send'))return plus('Atingiu o limite de novas conversas gratuitas.');return toast('Não foi possível enviar a mensagem.')}mi.value='';load();quota()}
async function profileView(){chrome('<h1 class="title">Perfil</h1>','profile');let [p,s]=await Promise.all([sb.from('profiles').select('*').eq('id',session.user.id).single(),sb.rpc('free_contact_status')]);if(p.error){document.getElementById('main').innerHTML='<div class="empty">'+esc(p.error.message)+'</div>';return}profile=p.data||profile;let st=s.data?.[0],ph=pic(profile.photo_path);document.getElementById('main').innerHTML='<h1 class="title">Perfil</h1><div class="profile"><div style="display:flex;gap:13px;align-items:center"><div class="av" style="width:66px;height:66px">'+(ph?'<img src="'+ph+'" alt="">':esc(ini(profile.display_name)))+'</div><div><div class="name" style="font-size:22px">'+esc(profile.display_name)+'</div><div class="small">'+esc(profile.area)+' · até '+profile.max_budget+' €/mês</div></div></div><div class="stats"><div class="stat"><span class="small">Novas conversas</span><b>'+(st?.plus?'∞':(st?.remaining??'—')+'/3')+'</b><span class="small">a cada 48h</span></div><div class="stat"><span class="small">Plano</span><b>'+(st?.plus?'Plus':'Grátis')+'</b><span class="small">beta</span></div></div><button class="btn red w" id="pl">CasaMatch+</button><div style="height:8px"></div><button class="btn ghost w" id="edit">Editar perfil</button><div style="height:8px"></div><button class="btn ghost w" id="lo">Sair</button></div><div class="safety"><b>Segurança primeiro</b><p>Nunca envie dinheiro ou documentos pelo chat. Confirme sempre pessoa, imóvel e contrato antes de assumir qualquer compromisso.</p><button class="link" id="safetylink" style="margin-top:8px">Ver dicas de segurança</button></div>';document.getElementById('pl').onclick=plus;document.getElementById('edit').onclick=onboard;document.getElementById('lo').onclick=logout;document.getElementById('safetylink').onclick=()=>legal('safety')}
function plus(msg='Não precisa pagar para usar. O Plus será para quem quer avançar sem esperar.'){pop('CasaMatch+',esc(msg),'<div class="plans"><div class="plan"><div><b>7 dias</b><div class="small">conversas ilimitadas · Rewind · ver likes</div></div><b>3,99 €</b></div><div class="plan"><div><b>30 dias</b><div class="small">tudo ilimitado</div></div><b>6,99 €</b></div></div><div class="notice">Durante o beta o pagamento ainda não está ativo.</div>')}
async function logout(){clearInterval(timer);await sb.auth.signOut();session=null;profile=null;cands=[];landing()}
(async()=>{let r=await sb.auth.getSession();session=r.data.session;if(session)after();else landing()})();
